"""initial tables

Revision ID: 179299e3f605
Revises: 
Create Date: 2026-10-04 20:10:41.138261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179299e3f605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trip_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('FEDERAL', 'WORK', 'SCHOOL', 'LEAGUE', 'CUSTOM', name='calendar_kind'), nullable=False),
    sa.Column('owner_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('ADULT', 'CHILD', 'GUEST', name='person_kind'), nullable=False),
    sa.Column('pto_balance', sa.Integer(), nullable=True),
    sa.Column('work_week', sa.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('managed_by_account_id', sa.Integer(), nullable=True),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('pto_balance IS NULL OR pto_balance >= 0', name='pto_not_negative'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['managed_by_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('effect', sa.Enum('DAY_OFF', 'BUSY', name='event_effect'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='event_dates_in_order'),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_event_calendar_id'), 'calendar_event', ['calendar_id'], unique=False)
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trip_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'person_id')
    )
    op.create_table('person_calendar',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('excluded_titles', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'calendar_id')
    )
    op.create_table('pto_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'COMMITTED', name='pto_status'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='pto_dates_in_order'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pto_block_person_id'), 'pto_block', ['person_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the one shared federal calendar. It has no event rows: the app
    # computes federal holidays from rules for whatever range is searched.
    op.execute("INSERT INTO calendar (name, kind) VALUES ('US Federal Holidays', 'FEDERAL')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pto_block_person_id'), table_name='pto_block')
    op.drop_table('pto_block')
    op.drop_table('person_calendar')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_calendar_event_calendar_id'), table_name='calendar_event')
    op.drop_table('calendar_event')
    op.drop_table('person')
    op.drop_table('calendar')
    op.drop_table('trip_group')
    op.drop_table('account')
    # ### end Alembic commands ###

    # Autogenerate forgets Postgres enum types; without this, upgrading again fails.
    for enum_type in ('pto_status', 'event_effect', 'person_kind', 'calendar_kind'):
        op.execute(f'DROP TYPE IF EXISTS {enum_type}')
