"""share links: secret invite and view-only links to a group

Revision ID: 4d934a61de77
Revises: a853008bd823
Create Date: 2026-10-07 00:18:54.324331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d934a61de77'
down_revision: Union[str, Sequence[str], None] = 'a853008bd823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('INVITE', 'VIEW', name='link_kind'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_account_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['trip_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_share_link_group_id'), 'share_link', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_link_group_id'), table_name='share_link')
    op.drop_table('share_link')
    # ### end Alembic commands ###
    # Autogenerate never drops enum types; without this, upgrading again fails.
    op.execute("DROP TYPE link_kind")
