"""pto renewal: yearly allowance, renewal month/day, carryover cap (all optional)

Revision ID: 6077da721ec5
Revises: 54c7def84071
Create Date: 2026-10-07 00:34:11.525460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6077da721ec5'
down_revision: Union[str, Sequence[str], None] = '54c7def84071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('pto_allowance', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('pto_renewal_month', sa.SmallInteger(), nullable=True))
    op.add_column('person', sa.Column('pto_renewal_day', sa.SmallInteger(), nullable=True))
    op.add_column('person', sa.Column('pto_carryover_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate doesn't see check constraints; these match orm.Person.
    op.create_check_constraint('allowance_not_negative', 'person', 'pto_allowance IS NULL OR pto_allowance >= 0')
    op.create_check_constraint('carryover_not_negative', 'person', 'pto_carryover_max IS NULL OR pto_carryover_max >= 0')
    op.create_check_constraint(
        'renewal_month_and_day', 'person', '(pto_renewal_month IS NULL) = (pto_renewal_day IS NULL)'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'pto_carryover_max')
    op.drop_column('person', 'pto_renewal_day')
    op.drop_column('person', 'pto_renewal_month')
    op.drop_column('person', 'pto_allowance')
    # ### end Alembic commands ###
