"""account ownership: who owns each group, and fast lookups of "my people"

Revision ID: a853008bd823
Revises: 56193c3d6d1e
Create Date: 2026-10-07 00:12:59.596751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a853008bd823'
down_revision: Union[str, Sequence[str], None] = '56193c3d6d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_person_linked_account_id'), 'person', ['linked_account_id'], unique=False)
    op.create_index(op.f('ix_person_managed_by_account_id'), 'person', ['managed_by_account_id'], unique=False)
    op.add_column('trip_group', sa.Column('owner_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trip_group_owner_account_id'), 'trip_group', ['owner_account_id'], unique=False)
    # Same name Postgres would pick on its own, written out so downgrade can find it.
    op.create_foreign_key('trip_group_owner_account_id_fkey', 'trip_group', 'account', ['owner_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trip_group_owner_account_id_fkey', 'trip_group', type_='foreignkey')
    op.drop_index(op.f('ix_trip_group_owner_account_id'), table_name='trip_group')
    op.drop_column('trip_group', 'owner_account_id')
    op.drop_index(op.f('ix_person_managed_by_account_id'), table_name='person')
    op.drop_index(op.f('ix_person_linked_account_id'), table_name='person')
    # ### end Alembic commands ###
