"""group trips: saved dates, with each adult's booking linked to the trip

Revision ID: cf1e8ce16769
Revises: 6077da721ec5
Create Date: 2026-10-09 01:17:24.598288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1e8ce16769'
down_revision: Union[str, Sequence[str], None] = '6077da721ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_by_account_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='trip_dates_in_order'),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['trip_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'start_date', 'end_date', name='one_trip_per_dates')
    )
    op.create_index(op.f('ix_trip_group_id'), 'trip', ['group_id'], unique=False)
    op.add_column('pto_block', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pto_block_trip_id'), 'pto_block', ['trip_id'], unique=False)
    op.create_foreign_key('pto_block_trip_id_fkey', 'pto_block', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    # Autogenerate doesn't see exclusion constraints; this matches orm.PTOBlock.
    # Upgrading fails if someone already has overlapping COMMITTED PTO: fix those rows first.
    # btree_gist (installed by 56193c3d6d1e) lets plain person_id sit in a GiST index.
    op.execute(
        "ALTER TABLE pto_block ADD CONSTRAINT no_double_booked_pto EXCLUDE USING gist "
        "(person_id WITH =, daterange(start_date, end_date, '[]') WITH &&) "
        "WHERE (status = 'COMMITTED')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE pto_block DROP CONSTRAINT no_double_booked_pto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pto_block_trip_id_fkey', 'pto_block', type_='foreignkey')
    op.drop_index(op.f('ix_pto_block_trip_id'), table_name='pto_block')
    op.drop_column('pto_block', 'trip_id')
    op.drop_index(op.f('ix_trip_group_id'), table_name='trip')
    op.drop_table('trip')
    # ### end Alembic commands ###
