/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holidays/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Holidays
         * @description Observed federal holidays that fall in `year` (including next year's
         *     New Year's when it's observed on Dec 31).
         */
        get: operations["holidays_holidays__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who's signed in, the people they manage, and the groups they can open.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Person */
        post: operations["create_person_people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Person Calendars
         * @description The calendars switched on for someone you manage. Another account's private
         *     calendar (a partner's, say) isn't listed: only shared ones and yours are.
         */
        get: operations["person_calendars_people__person_id__calendars_get"];
        put?: never;
        /**
         * Subscribe
         * @description Turn a calendar on for a person (or update their excluded holidays).
         */
        post: operations["subscribe_people__person_id__calendars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/pto-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Pto Block */
        post: operations["add_pto_block_people__person_id__pto_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Calendars
         * @description Shared calendars plus this account's own. `?kind=SCHOOL` lists school districts.
         */
        get: operations["list_calendars_calendars_get"];
        put?: never;
        /** Create Calendar */
        post: operations["create_calendar_calendars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{calendar_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_calendars__calendar_id__events_get"];
        put?: never;
        /** Add Event */
        post: operations["add_event_calendars__calendar_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Group */
        post: operations["create_group_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Group */
        get: operations["get_group_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Members
         * @description Bring more of your own people (a kid, a partner) into a group you're in.
         */
        post: operations["add_members_groups__group_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/members/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description The owner can remove anyone; a member can take their own people out.
         */
        delete: operations["remove_member_groups__group_id__members__person_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Optimize
         * @description Rank the vacation windows everyone in the group can share.
         */
        get: operations["optimize_groups__group_id__windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Links */
        get: operations["list_links_groups__group_id__links_get"];
        put?: never;
        /** Create Link */
        post: operations["create_link_groups__group_id__links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Link */
        delete: operations["revoke_link_groups__group_id__links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Link
         * @description What the link is for, before signing in: the group's name and who sent it.
         */
        get: operations["preview_link_links__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invite
         * @description Join the group with some of your own people (yourself, your kids).
         */
        post: operations["accept_invite_links__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{token}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shared View
         * @description Read-only plan for a view link: first names and dates, no account needed.
         */
        get: operations["shared_view_links__token__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_groups__group_id__trips_get"];
        put?: never;
        /**
         * Save Trip
         * @description Save dates for the group. Nobody's PTO changes until they book it.
         */
        post: operations["save_trip_groups__group_id__trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Trip
         * @description Whoever saved it, or the group's owner. Everyone's bookings for it go too
         *     (the database cascades the delete), so their PTO comes back.
         */
        delete: operations["delete_trip_groups__group_id__trips__trip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/trips/{trip_id}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book Trip
         * @description Book PTO for every adult you manage in the group. All of them or none:
         *     if anyone can't go, nothing is saved.
         */
        post: operations["book_trip_groups__group_id__trips__trip_id__booking_post"];
        /**
         * Cancel Booking
         * @description Take back your people's PTO for this trip. The saved trip stays.
         */
        delete: operations["cancel_booking_groups__group_id__trips__trip_id__booking_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{calendar_id}/events/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Events
         * @description Add many events in one go. All of them or none: one bad row saves nothing.
         */
        post: operations["add_events_calendars__calendar_id__events_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{calendar_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_calendars__calendar_id__events__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{calendar_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Calendar
         * @description Delete one of your calendars with all its events. People it was switched on
         *     for just lose it (the database removes those links).
         */
        delete: operations["delete_calendar_calendars__calendar_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/ics-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ics Preview
         * @description Read an .ics file and suggest events. Saves nothing: the screen shows the
         *     suggestions, and what the user ticks is saved through /events/bulk.
         */
        post: operations["ics_preview_calendars_ics_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptIn */
        AcceptIn: {
            /** Person Ids */
            person_ids: number[];
        };
        /** AddMembersIn */
        AddMembersIn: {
            /** Person Ids */
            person_ids: number[];
        };
        /** BulkEventsIn */
        BulkEventsIn: {
            /** Events */
            events: components["schemas"]["EventIn"][];
        };
        /** CalendarIn */
        CalendarIn: {
            /** Name */
            name: string;
            kind: components["schemas"]["CalendarKind"];
        };
        /**
         * CalendarKind
         * @enum {string}
         */
        CalendarKind: "FEDERAL" | "WORK" | "SCHOOL" | "LEAGUE" | "CUSTOM";
        /** CalendarOut */
        CalendarOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["CalendarKind"];
        };
        /**
         * Effect
         * @enum {string}
         */
        Effect: "DAY_OFF" | "BUSY";
        /** EventIn */
        EventIn: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Title */
            title: string;
            effect: components["schemas"]["Effect"];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            effect: components["schemas"]["Effect"];
        };
        /** GroupIn */
        GroupIn: {
            /** Name */
            name: string;
            /** Person Ids */
            person_ids: number[];
        };
        /** GroupOut */
        GroupOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "OWNER" | "MEMBER";
            /** People */
            people: components["schemas"]["MemberOut"][];
        };
        /** GroupSummary */
        GroupSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "OWNER" | "MEMBER";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Holiday */
        Holiday: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Name */
            name: string;
        };
        /** IcsEventOut */
        IcsEventOut: {
            /** Title */
            title: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            effect: components["schemas"]["Effect"];
            /** Selected */
            selected: boolean;
            /** Timed */
            timed: boolean;
        };
        /** IcsIn */
        IcsIn: {
            /**
             * Text
             * @description The contents of the .ics file
             */
            text: string;
            kind: components["schemas"]["CalendarKind"];
        };
        /** IcsPreviewOut */
        IcsPreviewOut: {
            /** Events */
            events: components["schemas"]["IcsEventOut"][];
            /** Skipped Recurring */
            skipped_recurring: number;
            /** Skipped Too Long */
            skipped_too_long: number;
            /** Skipped Invalid */
            skipped_invalid: number;
            /** Truncated */
            truncated: boolean;
        };
        /** InvitePreview */
        InvitePreview: {
            /** Group Name */
            group_name: string;
            /** Invited By */
            invited_by: string;
            kind: components["schemas"]["LinkKind"];
        };
        /** LinkIn */
        LinkIn: {
            kind: components["schemas"]["LinkKind"];
        };
        /**
         * LinkKind
         * @enum {string}
         */
        LinkKind: "INVITE" | "VIEW";
        /** LinkOut */
        LinkOut: {
            /** Id */
            id: number;
            kind: components["schemas"]["LinkKind"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Revoked */
            revoked: boolean;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Self Person Id */
            self_person_id: number | null;
            /** People */
            people: components["schemas"]["PersonOut"][];
            /** Groups */
            groups: components["schemas"]["GroupSummary"][];
        };
        /**
         * MemberOut
         * @description A person in a group. Balance and work week are None unless they're yours.
         */
        MemberOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["PersonKind"];
            /** Mine */
            mine: boolean;
            /** Pto Balance */
            pto_balance: number | null;
            /** Work Week */
            work_week: number[] | null;
        };
        /** NewLinkOut */
        NewLinkOut: {
            /** Id */
            id: number;
            kind: components["schemas"]["LinkKind"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Revoked */
            revoked: boolean;
            /** Token */
            token: string;
        };
        /** PTOBlockIn */
        PTOBlockIn: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            status: components["schemas"]["PTOStatus"];
        };
        /** PTOBlockOut */
        PTOBlockOut: {
            /** Id */
            id: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            status: components["schemas"]["PTOStatus"];
        };
        /**
         * PTOStatus
         * @enum {string}
         */
        PTOStatus: "PROPOSED" | "COMMITTED";
        /** PersonCalendarOut */
        PersonCalendarOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["CalendarKind"];
            /** Mine */
            mine: boolean;
            /** Enabled */
            enabled: boolean;
        };
        /** PersonIn */
        PersonIn: {
            /** Name */
            name: string;
            kind: components["schemas"]["PersonKind"];
            /** Pto Balance */
            pto_balance?: number | null;
            /**
             * Work Week
             * @description Mon=0 ... Sun=6
             * @default [
             *       0,
             *       1,
             *       2,
             *       3,
             *       4
             *     ]
             */
            work_week?: number[];
            /**
             * Is Self
             * @description This person is the signed-in user
             * @default false
             */
            is_self?: boolean;
            /**
             * Pto Allowance
             * @description PTO days granted each renewal
             */
            pto_allowance?: number | null;
            /** @description When PTO renews; omitted = Jan 1 */
            pto_renews_on?: components["schemas"]["RenewsOn"] | null;
            /**
             * Pto Carryover Max
             * @description Unused days that roll over
             */
            pto_carryover_max?: number | null;
        };
        /**
         * PersonKind
         * @enum {string}
         */
        PersonKind: "ADULT" | "CHILD" | "GUEST";
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["PersonKind"];
            /** Pto Balance */
            pto_balance: number | null;
            /** Work Week */
            work_week: number[];
            /** Pto Allowance */
            pto_allowance: number | null;
            pto_renews_on: components["schemas"]["RenewsOn"] | null;
            /** Pto Carryover Max */
            pto_carryover_max: number | null;
        };
        /** RenewsOn */
        RenewsOn: {
            /** Month */
            month: number;
            /** Day */
            day: number;
        };
        /** SearchOut */
        SearchOut: {
            /** Windows */
            windows: components["schemas"]["WindowOut"][];
            /** Free Long Weekends */
            free_long_weekends: components["schemas"]["WindowOut"][];
            /** Message */
            message: string | null;
        };
        /** SharedViewOut */
        SharedViewOut: {
            /** Group Name */
            group_name: string;
            /** People */
            people: string[];
            search: components["schemas"]["SearchOut"];
        };
        /** SubscribeIn */
        SubscribeIn: {
            /** Calendar Id */
            calendar_id: number;
            /**
             * Excluded Titles
             * @default []
             */
            excluded_titles?: string[];
        };
        /** TripIn */
        TripIn: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Label */
            label?: string | null;
        };
        /** TripOut */
        TripOut: {
            /** Id */
            id: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Label */
            label: string | null;
            /** Booked By */
            booked_by: string[];
            /** Can Book */
            can_book: boolean;
            /** Mine Booked */
            mine_booked: boolean;
            /** Can Delete */
            can_delete: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowOut */
        WindowOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Days */
            days: number;
            /** Pto Cost */
            pto_cost: {
                [key: string]: number;
            };
            /** Score */
            score: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    holidays_holidays__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    create_person_people_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    person_calendars_people__person_id__calendars_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonCalendarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_people__person_id__calendars_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_pto_block_people__person_id__pto_blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PTOBlockIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PTOBlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendars_calendars_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["CalendarKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_calendar_calendars_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_calendars__calendar_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_event_calendars__calendar_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_members_groups__group_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMembersIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_groups__group_id__members__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_groups__group_id__windows_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                min_days?: number;
                max_days?: number;
                sort?: "best_value" | "longest";
                limit?: number;
                distinct?: boolean;
            };
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_links_groups__group_id__links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_link_groups__group_id__links_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_link_groups__group_id__links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_link_links__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_links__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shared_view_links__token__view_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                min_days?: number;
                max_days?: number;
                sort?: "best_value" | "longest";
                limit?: number;
                distinct?: boolean;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips_groups__group_id__trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_trip_groups__group_id__trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_groups__group_id__trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_trip_groups__group_id__trips__trip_id__booking_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_groups__group_id__trips__trip_id__booking_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_events_calendars__calendar_id__events_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkEventsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_calendars__calendar_id__events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: number;
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_calendar_calendars__calendar_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ics_preview_calendars_ics_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IcsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcsPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
